//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var FibSum = function(lim) {
    u = 1;
    v = 2;
    w = 2;
    somme = 0
    while ( w < lim){
        if(w%2 == 0){
            somme += w;
        }
        w = u + v;
        u = v;
        v = w;
    }
    return somme;
}


console.log(FibSum(10));
console.log(FibSum(100));
console.log(FibSum(4000000));